prepare:
	brew install TrainScanner           #installed to system area.
	pip3 install pyinstaller
deploy:
	echo pyinstaller does not work with python3.6. Sorry.
	pyinstaller --noconfirm trainscanner_gui.macos.spec
clean:
	-rm -rf dist build
